name: Build sentence transformers extraction plugin

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}   
    - uses: actions/checkout@v3
    - name: Set up Python "3.10"
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Pinning to 0.7.2 is a temporary measure because of an issue with 0.7.3
        pip install hansken-extraction-plugin==0.7.2 sentence-transformers
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Build and label the Docker image
      run: |
        build_plugin bert_embeddings.py . bert-embeddings
    - name: Release the Docker image on branch main
      if: github.ref == 'refs/heads/main'
      run: |
        docker tag bert-embeddings ghcr.io/netherlandsforensicinstitute/bert-embeddings:latest
        docker push ghcr.io/netherlandsforensicinstitute/bert-embeddings:latest
